[build-system]
requires = ["scikit-build-core"]
build-backend = "scikit_build_core.build"

[project]
name = "acts"
version = "0.0.1"

[tool.scikit-build]
wheel.packages = [] # Manage installation with cmake
wheel.exclude = ["**.a", "**.sh", "**.cmake"]
wheel.license-files = ["LICENSE"]
build-dir = "build/{wheel_tag}"
build.verbose = true
cmake.args = ["--preset=python"]
logging.level = "DEBUG"
