histograms:
  outgoing_particles:
    nbins: 100
    min: 0
    max: 1e13

  vt:
    nbins: 100
    min: 0
    max: 20000

  "vx|vy":
    nbins: 100
    min: -15
    max: 15

  vz:
    nbins: 100
    min: -1000
    max: 1000

  eta:
    nbins: 100
    min: -15
    max: 15

  m:
    nbins: 100
    min: 0
    max: 2

  "p|pt":
    nbins: 100
    min: 0.0
    max: 200

  phi:
    nbins: 100
    min: -4.0
    max: 4.0

  "px|py":
    nbins: 100
    min: -5.0
    max: 5.0

  pz:
    nbins: 100
    min: -1000
    max: 1000

  q:
    nbins: 100
    min: -2.0
    max: 2.0

exclude:
  - event_id
  - particle_id
  - particle_type
  - process
  - vertex_id
  - vertex_primary
  - vertex_secondary
  - particle
  - generation
  - sub_particle
  - e_loss
  - total_x0
  - total_l0
  - number_of_hits
  - outcome
