name: Docs

on:
  push:
  pull_request:
    branches:
      - main
      - 'release/**'
      - 'develop/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  docs-old:
    runs-on: ubuntu-latest
    env:
      DOXYGEN_WARN_AS_ERROR: FAIL_ON_WARNINGS
      DOXYGEN_VERSION: "1.15.0"
      DOXYGEN_HASH: "0ec2e5b2c3cd82b7106d19cb42d8466450730b8cb7a9e85af712be38bf4523a1"
    steps:
      - uses: actions/checkout@v6

      - name: Install doxygen
        run: |
          curl -SL https://acts.web.cern.ch/ci/doxygen/doxygen-${{ env.DOXYGEN_VERSION }}.linux.bin.tar.gz -o doxygen-${{ env.DOXYGEN_VERSION }}.linux.bin.tar.gz
          echo "${{ env.DOXYGEN_HASH }}  doxygen-${{ env.DOXYGEN_VERSION }}.linux.bin.tar.gz" | sha256sum -c -
          tar xf doxygen-${{ env.DOXYGEN_VERSION }}.linux.bin.tar.gz
          mv doxygen-${{ env.DOXYGEN_VERSION }}/bin/doxygen /usr/local/bin/doxygen

      - name: Install dependencies
        run: >
          pip3 install --upgrade pip
          && pip install -r docs/old/requirements.txt

      - name: Build documentation
        run: >
          cd docs/old
          && sphinx-build
          -b html
          -d _build/doctrees/
          -j auto
          -W
          --keep-going
          -t run_doxygen
          -t lazy_autodoc
          -t white_papers
          -b linkcheck
          . _build/html/


      - uses: actions/upload-artifact@v6
        with:
          name: acts-docs-old
          path: docs/old/_build/html/

  docs:
    runs-on: ubuntu-latest
    container: ghcr.io/acts-project/ubuntu2404:83
    env:
      DOXYGEN_WARN_AS_ERROR: FAIL_ON_WARNINGS
      DOXYGEN_VERSION: "1.15.0"
      DOXYGEN_HASH: "0ec2e5b2c3cd82b7106d19cb42d8466450730b8cb7a9e85af712be38bf4523a1"
    steps:
      - uses: actions/checkout@v6

      - name: Install doxygen
        run: |
          curl -SL https://acts.web.cern.ch/ci/doxygen/doxygen-${{ env.DOXYGEN_VERSION }}.linux.bin.tar.gz -o doxygen-${{ env.DOXYGEN_VERSION }}.linux.bin.tar.gz
          echo "${{ env.DOXYGEN_HASH }}  doxygen-${{ env.DOXYGEN_VERSION }}.linux.bin.tar.gz" | sha256sum -c -
          tar xf doxygen-${{ env.DOXYGEN_VERSION }}.linux.bin.tar.gz
          mv doxygen-${{ env.DOXYGEN_VERSION }}/bin/doxygen /usr/local/bin/doxygen

      - name: Install dependencies
        uses: ./.github/actions/dependencies
        with:
          compiler: g++
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure
        run: >
          cmake -B build -S .
          --preset=github-ci
          -DCMAKE_INSTALL_PREFIX="${INSTALL_DIR}"
          -DACTS_BUILD_PLUGIN_ONNX=ON

      - name: Build documentation
        run: >
          cmake --build build --target docs

      - uses: actions/upload-artifact@v6
        with:
          name: acts-docs
          path: build/docs/html
