name: Docs

on:
  push:
  pull_request:
    branches:
      - main
      - 'release/**'
      - 'develop/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  docs:
    runs-on: ubuntu-latest
    env:
      DOXYGEN_WARN_AS_ERROR: FAIL_ON_WARNINGS
      DOXYGEN_VERSION: "1.15.0"
      DOXYGEN_HASH: "0ec2e5b2c3cd82b7106d19cb42d8466450730b8cb7a9e85af712be38bf4523a1"
    steps:
      - uses: actions/checkout@v6

      - name: Install doxygen
        run: |
          curl -SL https://acts.web.cern.ch/ci/doxygen/doxygen-${{ env.DOXYGEN_VERSION }}.linux.bin.tar.gz -o doxygen-${{ env.DOXYGEN_VERSION }}.linux.bin.tar.gz
          echo "${{ env.DOXYGEN_HASH }}  doxygen-${{ env.DOXYGEN_VERSION }}.linux.bin.tar.gz" | sha256sum -c -
          tar xf doxygen-${{ env.DOXYGEN_VERSION }}.linux.bin.tar.gz
          mv doxygen-${{ env.DOXYGEN_VERSION }}/bin/doxygen /usr/local/bin/doxygen

      - name: Install dependencies
        run: >
          pip3 install --upgrade pip
          && pip install -r docs/requirements.txt

      - name: Build documentation
        run: >
          cd docs
          && sphinx-build
          -b html
          -d _build/doctrees/
          -j auto
          -W
          --keep-going
          -t run_doxygen
          -t lazy_autodoc
          -t white_papers
          -b linkcheck
          . _build/html/


      - uses: actions/upload-artifact@v5
        with:
          name: acts-docs
          path: docs/_build/html/
